name: Sanity check (AI ref kits)

on:
  schedule:
    - cron: "0 2 * * *"
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  find-subprojects:
    runs-on: ubuntu-latest
    outputs:
      gradio: ${{ steps.categorize-subprojects.outputs.gradio }}
      webcam: ${{ steps.categorize-subprojects.outputs.webcam }}
      python: ${{ steps.categorize-subprojects.outputs.python }}
      notebook: ${{ steps.categorize-subprojects.outputs.notebook }}
      agentic: ${{ steps.categorize-subprojects.outputs.agentic }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine subprojects to test
        id: find-updates
        uses: ./.github/reusable-steps/find-updates
        with:
          dir: ai_ref_kits
          ci_config_file: sanity-check-kits.yml

      - name: Categorize subprojects
        id: categorize-subprojects
        uses: ./.github/reusable-steps/categorize-projects
        with:
          subprojects: ${{ steps.find-updates.outputs.subproject_dirs }}

  python:
    needs: find-subprojects
    if: ${{ needs.find-subprojects.outputs.python != '[]' }}

    uses: ./.github/workflows/reusable-sanity-python.yml

    with:
      subprojects: ${{ needs.find-subprojects.outputs.python }}
      python_versions: '["3.10", "3.13"]'

  webcam:
    needs: find-subprojects
    if: ${{ needs.find-subprojects.outputs.webcam != '[]' }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2025]
        python: ["3.10", "3.13"]
        subproject: ${{ fromJson(needs.find-subprojects.outputs.webcam) }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/reusable-steps/setup-os

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: ./.github/reusable-steps/setup-python
        with:
          python: ${{ matrix.python }}
          project: ${{ matrix.subproject }}

      - name: Run webcam demo
        run: |
          cd ${{ matrix.subproject }}
          if [ "${{ runner.os }}" == "Linux" ]; then
            xvfb-run python main.py --stream sample_video.mp4
          else
            python main.py --stream sample_video.mp4
          fi

  notebook:
    needs: find-subprojects
    if: ${{ needs.find-subprojects.outputs.notebook != '[]' }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, windows-2025]
        python: ["3.10", "3.13"]
        subproject: ${{ fromJson(needs.find-subprojects.outputs.notebook) }}

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/reusable-steps/setup-os

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: ./.github/reusable-steps/setup-python
        with:
          python: ${{ matrix.python }}
          project: ${{ matrix.subproject }}

      - name: Run notebook
        run: |
          cd ${{ matrix.subproject }}
          jupyter nbconvert --to notebook --execute *.ipynb